Update REARDME.md to include Traffic Influnce
camaraproject/EdgeCloud pull request #67
Opened 2023-02-22 07:59 UTC by FabrizioMoggio

Included the Traffic Influence feature in the Edge Cloud API Family description

2023-03-01 09:27 UTC, Kevsy commented on README.md
> +  * Influece the traffic routing from the user device toward the Edge instance of the Application
Typo: influece->influence

2023-03-01 09:28 UTC, Kevsy requested changes
One typo to fix: influece->influence

2023-03-16 10:10 UTC, crissancas approved these changes

2023-03-16 10:12 UTC, gunjald approved these changes

2023-03-21 14:52 UTC, FabrizioMoggio commented
@Kevsy I have fixed the Typo

2023-03-21 15:24 UTC, Kevsy approved these changes

2023-03-21 15:28 UTC, merged